### ISSUE TITLE
스프링 서버 테이블명 변경

### ISSUE THREAD

**Issue by dreamcometrue-color** [EY-Solution/EY-Solution.github.io#1]
안녕하세요.

데이터베이스의 테이블명을 프로젝트에 따라 변경하고 싶습니다.
스프링 서버에서 application.yml에 환경 변수를 추가하는 방법으로 테이블명을 수정할 수 있을까요?
변경 가능하다면 적절한 방법을 추천해 주십시오.

도움에 미리 감사드립니다.

**Comment by EY-Solution** [comment]
안녕하세요.
아래 링크의 가이드 내용 중 Mapping Override 항목을 참고하시면 됩니다.
- https://vectorx.notion.site/VxTableEntityMapper-1f400926465544e996af6b3dcc114a42 


관련 코드 또한 Spring Template 에 추가해놓았습니다. 다만 구동을 위해 테이블 명은 그대로 유지한 상태이니 참고하시기 바랍니다.

- Spring BO Template : https://github.com/EY-Solution/vectorx-templates-spring-bo
