### ISSUE TITLE
Pre-transform error

### ISSUE THREAD

**Issue by dreamcometrue-color** [EY-Solution/EY-Solution.github.io#10]
안녕하세요

yarn run dev 실행할 때 간혹 다음과 같은 에러가 납니다
어떤 경우에 발생하는지 파악이 안됩니다

소스를 변경했을 때 yarn run dev 재실행해야 반영이 됩니다
혹시 어떤 경우에 발생하는지 알 수 있을까요?

 ERROR  Pre-transform error: [@vue/compiler-sfc] Failed to resolve import source "#vectorx/nuxt/composables/components/file".   오후 12:23:06  

D:/WorkSpace/EY/Octo/node_modules/@vectorx/nuxt/src/management/composables/components/file.ts
24 |    return defineVxFileUploaderComponent(props, {
25 |      findFileGroup(fileGrpId) {
26 |        return $vx.management.store.initData.fileGroups.find(fg => fg.fileGrpId === fileGrpId)
   |                                                       ^^^^^^^^^^^^^^^^^^^^^^^^
27 |      },
28 |      ...options,

 ERROR  Pre-transform error: [@vue/compiler-sfc] Failed to resolve import source "#vectorx/nuxt/composables/components/file".   오후 12:23:06  

D:/WorkSpace/EY/Octo/node_modules/@vectorx/nuxt/src/management/composables/components/file.ts
23 |  ) => {
24 |    return defineVxFileUploaderComponent(props, {
25 |      findFileGroup(fileGrpId) {
   |            ^^^^^^^^^^^^^^^^^^^^
26 |        return $vx.management.store.initData.fileGroups.find(fg => fg.fileGrpId === fileGrpId)
   |  ^^^
27 |      },

**Comment by keymasroy** [comment]
nuxt 버전 업그레이드 후 alias를 간혹 못찾는 현상이 있어 alias 참조 구조를 일부 수정하였습니다.
`24.1.6-alpha.8` 버전을 적용하시면 됩니다.

https://github.com/EY-Solution/vectorx-templates-nuxt-kendo-ui-bo/commit/48b6740cd77992fd7628ce2484d8c54234c7cf6f
