### ISSUE TITLE
사용자 ID, IP

### ISSUE THREAD

**Issue by dreamcometrue-color** [EY-Solution/EY-Solution.github.io#11]
안녕하세요

프레임워크 상에서 사용자 ID와 IP를 알아낼 수 있는 방법을 알 수 있을까요?

고맙습니다

**Comment by keymasroy** [comment]
프레임워크 상에서 사용자의 정보를 조회하는 방법은 다음과 같습니다.

1. Nuxt
아래 가이드 링크에서 안내하고 있는 `useVxManagementUser` 메소드를 사용하면 됩니다.
해당 객체는 사용자 정보를 object형태로 반환하는데, 아래 속성을 통해 조회 가능합니다.
- sub : 로그인한 사용자 아이디
- accessInfo.userIp : 사용자 IP 주소

📌 참고 : https://vectorx.notion.site/2f9baf3a03c3450599f7841975a1466c#1b734499d9af4a08a0564baea8f9c955

2. Spring
프레임워크에서는 Spring Security를 사용하고 있어 `SecurityContextHolder`를 통해 현재 인증 정보를 조회할 수 있습니다.
하지만 형변환 등을 통해 사용자 정보를 확인해야 하므로 유틸리티 메소드를 제작하여 사용하는 것을 권장하고 있습니다.
아래 가이드 링크를 참고하여 제작 후, 사용하시면 됩니다.

📌 참고 : https://vectorx.notion.site/aff63d0da30240d48551ee51c81d6b2e

Request 사용자의 IP 주소는 `VxWebUtils.getClientIp()` 메소드를 사용하여 조회 가능합니다.
