### ISSUE TITLE
시스템 메뉴

### ISSUE THREAD

**Issue by dreamcometrue-color** [EY-Solution/EY-Solution.github.io#12]
안녕하세요

프레임워크의 화면 "시스템 > 메뉴 관리"에서  개발이 완료되지 않았던 시스템 메뉴를 삭제하였습니다.

DB의 VECTORX_MNU 테이블에서 해당 메뉴의 DEL_YN 컬럼 값을 'N'으로 수정하고
"시스템 > 권한 관리"에서 권한을 주었습니다.

"시스템 > 메뉴 관리"에서는 그 메뉴가 나타나지만
프레임워크의 화면에서 해당 메뉴가 나타나질 않습니다.

이를 복구하려면 어떻게 해야 할까요?

**Comment by keymasroy** [comment]
프레임워크에서는 메뉴 정보를 브라우저에 캐시합니다. (자주 변경되는 정보가 아니므로)
가장 간단하게 메뉴 정보를 다시 불러오기 원하시면 브라우저 종료 후 다시 접속하시면 됩니다.

혹은 아래 링크되어 있는 관리자 설정 메뉴로 이동하셔서 캐시를 모두 지우시면 됩니다.

📌 관리자 설정 메뉴 가이드 : https://vectorx.notion.site/a48f8b9e3a96404792b30dce551ccf81
