### ISSUE TITLE
로딩 이미지

### ISSUE THREAD

**Issue by dreamcometrue-color** [EY-Solution/EY-Solution.github.io#13]
안녕하세요

개발 하면서 로딩 이미지를 바꾸고 싶습니다.
vx-favicon.ico 이 파일 이미지인듯 한데 이 파일을 바꾸는 환경 설정이 있을까요?

고맙습니다.

**Comment by keymasroy** [comment]
안녕하세요. 아래의 가이드를 참고하시면 됩니다.
- favicon  : https://vectorx.notion.site/Favicon-6a3dba3c70224967b3d4cb6e1f801424
- loading bar : https://vectorx.notion.site/Loading-Bar-78689e90b1b84f7db7c5cdeb1a7836e5

**Comment by dreamcometrue-color** [comment]
favicon은 덕분에 해결하였습니다.
loading bar는 잘 모르겠습니다. 혹시 예제 있을까요?

고맙습니다.

**Comment by EY-Solution** [comment]
템플릿 프로젝트에 로딩 바 변경 예제를 적용해놓았습니다.
아래 링크를 참고하시면 됩니다.

- 로딩 템플릿 적용
  - app.vue : https://github.com/EY-Solution/vectorx-templates-nuxt-kendo-ui-bo/blob/main/app.vue
  - components/global/loading-bar.vue : https://github.com/EY-Solution/vectorx-templates-nuxt-kendo-ui-bo/blob/main/components/global/loading-bar.vue

- SPA Loading Template 적용
  - app/spa-loading-template.html : https://github.com/EY-Solution/vectorx-templates-nuxt-kendo-ui-bo/blob/main/app/spa-loading-template.html

  - SPA Loading Template 가이드 : https://vectorx.notion.site/SPA-Loading-Template-2ffeda2fd58e4895b70f8e6832645819?pvs=74
