### ISSUE TITLE
24.1.6-alpha.10 버전에서 날짜 피커

### ISSUE THREAD

**Issue by dreamcometrue-color** [EY-Solution/EY-Solution.github.io#14]
안녕하세요

언제나 소중한 답변해주시는 것에  감사드립니다.

24.1.6-alpha.3 버전을 사용하는 컴퓨터에서는 괜찮은데
24.1.6-alpha.10 버전을 사용하는 컴퓨터에서는 다음과 같은 오류가 발생합니다
날짜 피커에서 문제가 생기는 듯 합니다.

에러메시지는 다음과 같습니다.
[error_message.txt](https://github.com/user-attachments/files/16512414/error_message.txt)

고맙습니다.

**Comment by EY-Solution** [comment]
안녕하세요. 테스트 결과 프레임워크 관련 코드에서 오류 발생이 확인되지 않습니다.
아래 내용의 추가 확인이 필요합니다.

1. `@progress/kendo-vue-dateinputs` 모듈의 설치 버전
    - node_modules/@progress/kendo-vue-dateinputs/package.json에서 확인 가능

2. 문제가 발생하는 영역의 소소 코드

우선 상황 재연이 되어야 패치가 가능할 것으로 보여 위의 내용 답변 부탁 드립니다.

**Comment by dreamcometrue-color** [comment]
안녕하세요

모듈 버전은 3.14.2입니다. 
영역 소스코드는 다음과 같습니다.
[A1010.zip](https://github.com/user-attachments/files/16538230/A1010.zip)

이미지에서 보이는 것처럼 상단 일자 오른쪽에 입력칸이 나타나지 않습니다.
![VxKDateRangePicker](https://github.com/user-attachments/assets/91679541-ca96-40f9-a5be-4edf76b67083)

컴퓨터에 윈도우 다시 설치 후, Git, nvm, Node.js, VSCode, JavaSDK, IntelliJ 등만 설치하고 실행해봐도 마찬가지입니다.
저도 이상하여 다른 컴퓨터에서 실행했더니 잘 되는 컴퓨터도 있었습니다.

고맙습니다.

**Comment by EY-Solution** [comment]
안녕하세요.
공유해주신 코드로 내부 테스트를 진행해보았으나 오류가 발생하지 않았습니다.
아무래도 환경적인 문제로 판단됩니다.

다음의 명령어를 입력하여 캐시 정보를 삭제 후 구동해보시거나 node_modules 디렉토리 제거 후 라이브러리를 재 설치 후 구동해보시기 바랍니다.

```bash
yarn cache clean

npx nuxi cleanup
```
