### ISSUE TITLE
권한 기능

### ISSUE THREAD

**Issue by dreamcometrue-color** [EY-Solution/EY-Solution.github.io#15]
안녕하세요

samples/post 에서 기능별로 권한을 달리 주고 싶으면 어떻게 할수 있을지에 관하여 문의드립니다.

만약 조회 기능, 저장 기능, 수정 기능, 삭제 기능 등에 사용자별로 다르게 권한을 주어야 한다면 어떻게 구현할지 잘 모르겠습니다.
혹시 예제 없을까요?

고맙습니다.

**Comment by keymasroy** [comment]
안녕하세요. 기능별로 권한을 설정하는 가이드를 별도로 제작하였으니 아래 링크를 참고해주시면 됩니다.
- https://vectorx.notion.site/103e48c3bcbb43e391e27f4fbd7fc0ef
