### ISSUE TITLE
PDF 열기

### ISSUE THREAD

**Issue by dreamcometrue-color** [EY-Solution/EY-Solution.github.io#16]
안녕하세요
더운 날씨에도 건강히 지내시죠?

지난번에 추천해주셨던 것처럼 Jasper(레포트 툴)를 사용하여 만들고 있습니다.

다음과 같이 서버를 만들어 테스트했습니다.
[report.zip](https://github.com/user-attachments/files/16633594/report.zip)
이 서버의 컨트롤러 SampleController.java를 VectorX 프레임워크에 넣고 실행하면
소스 내의 클라이언트에서 호출하는 방법대로 
Vue 클라이언트에서 window.open('/api/publish/download/1234') 하면 다운로드는 잘 됩니다.

하지만 window.open('/api/publish/view/1234')하면 에러가 납니다.
![image](https://github.com/user-attachments/assets/1bfe89fd-bdf5-4025-8de9-f16722599628)
이미지에서 
resultCode는 FC02 이고
resultMessage는 class me.vectorx.spring.mvc.rest.model.VxRestResult cannot be cast to class [B (me.vectorx.spring.mvc.rest.model.VxRestResult is in unnamed module of loader 'app'; [B is in module java.base of loader 'bootstrap') 입니다.

이 에러를 어떻게 해결하면 좋을까요?
혹시 스트림을 받는 API가 따로 있을까요?
다음과 같이 새 창에 PDF 파일을 여는 방법이 필요합니다.

![image](https://github.com/user-attachments/assets/efb31dc1-0d23-40be-a266-a0e91bb07efe)

고맙습니다.

**Comment by keymasroy** [comment]
안녕하세요. 문의하신 내용 답변 드립니다.

1. ClassCastException
프레임워크의 API 처리는 응답 표준화를 위해 Wrapping 되는 형태로 기본 처리됩니다. 따라서 위와 같이 바이너리 응답 컨트롤러는 커스톰 설정이 필요합니다.
- 참고 가이드 : https://vectorx.notion.site/API-c62ab93bc1e9471fa2875d927b7822f2#5e4e87b6e2f74f7a8f6b64e497275681

가장 쉽게 설정할 수 있는 방법은 아래와 깉이 컨트롤러 메소드에 `@VxExcludeRestApiWrapping` annotation을 추가하면 됩니다.
```java
@VxExcludeRestApiWrapping
@GetMapping(value = "/api/publish/view/{qrcode}")
public ResponseEntity<byte[]> viewQrCode(@PathVariable("qrcode") String qrcode) throws Exception, JRException {
....
}
```

2. 브라우저 상에 바로 열리는 설정
예제로 세팅하신 컨트롤러의 코드를 아래와 같이 변경하면 될 것 같습니다.
```java

// 원본 코드
response.setContentType("application/octet-stream");
response.setContentLength(data.length);
response.setHeader("Content-Disposition","attachment; fileName=\"TempReportKitWms.pdf\";");
response.setHeader("Content-Transfer-Encoding","binary");

// 수정 코드
response.setContentType("application/pdf");
response.setContentLength(data.length);
```
위와 같이 하시면 URL을 바로 오픈하였을 때 브라우저에서 노출됩니다.

**Comment by dreamcometrue-color** [comment]
주말에도 답변을 주시다니 고맙습니다.
답 주신대로 하였더니 새로운 창에 잘 열리고 브라우저 콘솔에도 오류 메시지 없이 열립니다.
[SampleController.zip](https://github.com/user-attachments/files/16646942/SampleController.zip)


그런데 다음과 같은 오류 메시지가 서버 로그에 남습니다.
Caused by: java.lang.IllegalAccessException: class net.sf.jasperreports.engine.util.ClassUtils cannot access class com.sun.org.apache.xerces.internal.util.XMLGrammarPoolImpl (in module java.xml) because module java.xml does not export com.sun.org.apache.xerces.internal.util to unnamed module @3c0a50da

이 에러는 어떻게 처리하면 좋을까요?

고맙습니다

**Comment by keymasroy** [comment]
jasperreport가 Java 버전에 따른 이슈가 있나보네요.
- 참조 : https://github.com/TIBCOSoftware/jasperreports/issues/61

위의 링크에도 언급되어 있지만 jasperreports.properties 파일에 net.sf.jasperreports.compiler.xml.parser.cache.schemas=false 설정을 추가해보시는게 어떨까 합니다.
