### ISSUE TITLE
인터페이스

### ISSUE THREAD

**Issue by dreamcometrue-color** [EY-Solution/EY-Solution.github.io#17]
주말에도 답변을 달아주시다니 매번 고맙습니다.

저희가 SAP, 자동 창고, 구매시스템 등과 인터페이스를 해야합니다.
VectorX 프레임워크에서 제공하는 인터페이스 매뉴얼을 보면
인터페이스를 어떻게 구성하고, 관리하는가에 대하여 알 수 있었습니다.

이 인터페이스를 스케줄에 따라 처리하는 경우도 있고
웹 화면 상에서 버튼을 클릭하여 즉시 처리하는 경우도 있습니다.

이러한 경우에 어떻게 실행할 수 있는지 모르겠습니다.

고맙습니다.

**Comment by keymasroy** [comment]
프레임워크에서 제공하는 인터페이스 관련 기능은 2가지가 있습니다.
- 관리자 프로그램을 사용한 인터페이스 로그 및 설정 처리
- REST, SOAP 인터페이스 호출 처리 : https://vectorx.notion.site/VxInterfaceTemplate-8d18084495654e0490370f828c95853a

인터페이스의 실시간 처리는 위에 언급되어 있는 REST, SOAP 인터페이스 호출 처리 기능을 사용하시면 됩니다.
SAP 인터페이스 호출 부분은 모듈화 하기가 애매한 영역이라 프레임워크에서 별도로 인터페이스 기능을 제공하지는 않습니다만 https://github.com/saro-lab/sap-jco-manager 를 참고하셔서 구현하시면 됩니다.

스케쥴에 따라 처리하는 경우는 프레임워크 배치 기능을 사용하시거나 스프링 Schedule 기능을 사용하시면 됩니다.
- 참고 : https://spring.io/guides/gs/scheduling-tasks
