### ISSUE TITLE
쿠키

### ISSUE THREAD

**Issue by dreamcometrue-color** [EY-Solution/EY-Solution.github.io#18]
안녕하세요

이번에는 쿠키에 관하여 질문하려 합니다

특정한 값을 모든 클라이언트에서 사용하기 위하여 사용하고 싶은데
어떻게 사용하면 될까요?

고맙습니다

**Comment by keymasroy** [comment]
안녕하세요.
질문 하신 내용에 대해서 좀 더 구체적으로 설명해주셨으면 합니다.

1. 쿠키를 쓰는 주체는 어디인가요? (서버, 클라이언트)

2. 쿠키 값이 수시로 변경되는가요?

3. 쿠키를 읽는 주체는 어디인가요? (서버, 클라이언트 혹은 둘다)

4. 쿠키를 언제 읽어야 하나요?

5. 쿠키가 삭제되는 시점과 위치는 어떻게 되나요?

전반적으로 쿠키 값을 핸들링하는 라이프 사이클 정보를 주시면 좀 더 구체적으로 답변이 가능합니다.

**Comment by dreamcometrue-color** [comment]
1. 쿠키는 서버에서 쓰려고 합니다
2. 쿠키 값은 고정된 값을 사용하려고 합니다.
3. 쿠키를 클라이언트에서 읽어서 사용하려고 합니다
4. 서버 REST API 호출하는 시점에 읽을 수 있으면 됩니다
5. 쿠키 삭제는 크게 중요하지 않을 것 같습니다.

반드시 쿠기가 아니라도 상관 없습니다.

VectorX 프레임워크의 억세스 토큰처럼  서버에서 지정한 값을  클라이언트에서 보관하고 있다가 필요할 때 그  값을 사용할 수 있으면 좋겠습니다.

**Comment by keymasroy** [comment]
안녕하세요. 
HTTP 쿠키 관련한 가이드를 추가하여 안내 드립니다.

https://vectorx.notion.site/HTTP-Cookie-94386830fabe4591b9a54c9699f875e4

**Comment by dreamcometrue-color** [comment]
혹시 로그인 과정에서 쿠키를 추가하려면 어떻게 하면 좋을까요?

**Comment by keymasroy** [comment]
인증 커스토마이징 관련 설정을 템플릿 프로젝트에 추가하였습니다.
- 가이드 : https://github.com/EY-Solution/vectorx-templates-spring-bo?tab=readme-ov-file#%EC%9D%B8%EC%A6%9D%EC%84%A4%EC%A0%95
- 소스 코드 : https://github.com/EY-Solution/vectorx-templates-spring-bo/blob/main/src/main/java/me/vectorx/spring/templates/bo/config/AuthenticationConfiguration.java
