### ISSUE TITLE
VectorX 서버에 Framework UI에서 접근이 아닌 안드로이드, 플러터 등에서의 접근

### ISSUE THREAD

**Issue by dreamcometrue-color** [EY-Solution/EY-Solution.github.io#2]
안녕하세요

프로젝트를 진행하면서 웹이 아닌 안드로이드나 플러터를 사용하여 안드로이드에서 구동하는 앱을 만들고자 합니다.
프레임워크에서 제공하는 기본 기능이 아닌 새로 만드는 컨트롤러, 서비스, 매퍼 등을 통하여 앱에서 접근하려고 합니다.

서버쪽 로그를 보면 로그인을 하기위하여 /api/authentication/login path에 POST 메소드로 호출하는 것 같습니다.
VSCdoe의 REST Client Extension을 사용하여 테스트로 바디에 { "userId": "admin", "userPassword": "admin" } 를 담아 보내봤습니다.
401 권한 없음 응답이 돌아왔습니다.

1. UI 화면에서 말고 다른데서는  REST 호출을 어떻게 하면 될까요?
2. 또 반환되는 토큰을 어떻게 담아 다른 컨트롤러를 호출할 수 있을까요?
3. Node에 관련한 문서를 보다보면 $vx.api.call 와 같이 $vx로 시작하는 메소드, 변수 같은 것이 많이 나오던데 그에 관련한 node_module 파일 찾는 방법이 있을까요?

고맙습니다.

**Comment by keymasroy** [comment]
안녕하세요.
문의 하신 내용에 대해 답변 드립니다.

1. REST 호출 규약
우선 인증 관련 API 호출 규약에 대해 문의 주셨는데요. 위의 401 오류 현상은 권한 문제로 Controller 커스토마이징이 있을 경우, 로그인 API에 대한 추가 설정이 필요합니다. 아래 가이드를 확인하시면 됩니다.
- https://vectorx.notion.site/178f17b29fe0430ba6c45476485714da#989ec1da9cb44545b820797d2700669a

2. 토큰 처리
API 호출 시에는 HTTP Header를 사용하시면 됩니다. 관련 가이드는 아래 링크를 확인해주세요.
- https://vectorx.notion.site/JWT-6d741ccc82bd4d8a83cb6087c6d5df26#62049df9535e441f97cb3d13551f7153

3. Node 관련 소스 코드
$vx로 시작하는 기능은 Vx 플러그인으로 제작되어 있으며, @vectorx/nuxt 라이브러리에서 확인할 수 있습니다.
정확한 코드 위치는 `@vectorx/nuxt/src/plugins/vx.ts` 입니다.
