### ISSUE TITLE
화면이 없는 컨트롤러에 권한 주기

### ISSUE THREAD

**Issue by dreamcometrue-color** [EY-Solution/EY-Solution.github.io#22]
안녕하세요

회사에서 MSSQL 프로시저를 많이 사용합니다
어느 컨트롤러에서나 사용할만한 프로시저를 공통적으로 관리하기 위하여 다음과 같이 컨트롤러를 따로 만들 경우 

```
@Api(tags = "공통 프로시저 API", produces = "application/json")
@RestController
@RequestMapping("/api/common/procedure")
@VxPermission(roles= {VxTemplateProgramIds.COMMON_PROCEDURE})
public class ProcedureController {
	@Autowired
	private ProcedureService procedureService;

	@ApiOperation("Posts")
	@PostMapping("/posts")
	public Object[] posts(@RequestBody ProcedureEntity.Condition condition) {
		return this.procedureService.posts(VxRestUtils.getCurrentApiHeader(), condition);
	}

	@ApiOperation("MultiPosts")
	@PostMapping("/multiPosts")
	public Object[] multiPosts(@RequestBody ProcedureEntity.MultiCondition multiCondition) {
		return this.procedureService.multiPosts(multiCondition);
	}
}

```
이 프로시저 호출하는 컨트롤러의 권한 설정을 어떻게 하면 좋을까요?

![image](https://github.com/user-attachments/assets/95f06173-b14b-43cb-ad3d-9db53636b81d)
이와 같이 설정하고 사용하면 권한 설정이  로그인 하지 않은 사용자는 접근이 막히는 것을 확인하였는데 이렇게 사용해도 괜찮을까요?

더 적절한 방법이 있을까요?

**Comment by keymasroy** [comment]
안녕하세요.
위와 같은 설정은 사실 세팅하기 나름이라 정답이 있진 않습니다.
다만 설정 또는 프로그래밍 방식으로 권한을 제어하는 다른 기능 들이 존재하므로 함께 검토 해보시면 될 것 같습니다.

https://vectorx.notion.site/792f5dd6348e42d79ec82672b80fce4e#0bb94d26d22647c9b97c4ee174866dee
