### ISSUE TITLE
MSSQL 스키마 VECTORX_MNU

### ISSUE THREAD

**Issue by dreamcometrue-color** [EY-Solution/EY-Solution.github.io#3]
안녕하세요
MSSQL을 사용하데 있어서 문의합니다.

schema-h2.sql 에서 VECTORX_MNU의 PRV_VIEW_YN  컬럼 내용입니다.
   PRV_VIEW_YN     CHARACTER(1)       NULL     DEFAULT 'N', -- 개인정보_조회_여부
schema-mssql.sql에서 해당하는 같은 부분입니다.
	[PRV_VIEW_YN] [CHAR](1) NOT NULL DEFAULT 'N',  /* 개인정보_조회_여부 */
H2의 경우 NULL이고 MSSQL의 경우 NOT NULL입니다.

MSSQL에서 새로운 메뉴를 만들 때 쿼리가 NULL로 들어가면서 SQL에러가 납니다.

이를 H2의 경우와 마찬가지로 NOT NULL을 NULL로 해서 사용해도 괜찮을까요?

고맙습니다.

**Comment by EY-Solution** [comment]
PRV_VIEW_YN 필드는 NOT NULL 이 맞습니다.
h2 스키마가 잘못되어 수정해놓았습니다.

다만 어플리케이션에서 null이 유입되어 문제가 발생하고 있는 상태이므로 다음 중 하나를 선택하여 조치하시면 됩니다.
1) PRV_VIEW_YN 필드를 NULL 로 수정
2) Spring 프레임워크 24.1.9-SNAPSHOT.1  버전 적용
- 24.1.9-SNAPSHOP.1 버전은 https://github.com/EY-Solution/vectorx-templates-spring-bo 에서 확인 가능합니다.


공식 패치는 Spring 24.1.9 버전에 적용될 예정입니다.
