### ISSUE TITLE
레포트 툴

### ISSUE THREAD

**Issue by dreamcometrue-color** [EY-Solution/EY-Solution.github.io#5]
안녕하세요

레포트 툴이 필요한데 프레임워크에서 사용하는 레포트 툴이 있을까요?

고맙습니다

**Comment by EY-Solution** [comment]
안녕하세요. 
현재 기준으로는 프레임워크에서 제공 또는 사용하는 레포트 툴은 없습니다.

프로젝트 요건에 맞게 선택하여 사용하시면 됩니다.
