### ISSUE TITLE
WAR 빌드 및 배포

### ISSUE THREAD

**Issue by dreamcometrue-color** [EY-Solution/EY-Solution.github.io#6]
안녕하세요

WAR 배포에 관하여  질문 드립니다.

다음과 같이 하였는데 로그에서 에러가 계속 나옵니다.

ApplicationRunner.java 수정
@SpringBootApplication
public class ApplicationRunner extends VxServletApplicationRunner {
	public static void main(String[] args) throws IOException {
		VxServletApplicationRunner.run(ApplicationRunner.class, args);
//		final SpringApplicationBuilder builder = new SpringApplicationBuilder(ApplicationRunner.class);
//		VxServletApplicationRunner.run(ApplicationRunner.class, builder, args);
	}
}

기존에 있던 ApllicationRunner.java 파일의 main에 있던 2줄 지우고 builder를 빼고 VxServletApplicationRunner.run(ApplicationRunner.class, args);를 추가하였습니다.

build.gradle 수정
plugins에 id 'war'를 추가하였습니다.
다음 2줄도 추가하였습니다.
bootWar.enabled = false
war.enabled = true
build.gradle 파일이 다음과 같이 되었습니다.
plugins {
	id 'java'
  id 'eclipse'
	id 'org.springframework.boot' version '2.7.18'
    // plugins에 war 추가
    id 'war'
}

apply plugin: 'io.spring.dependency-management'

group = 'me.vectorx.templates'
version = '1.0.0'

bootWar.enabled = false
war.enabled = true

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
    withSourcesJar()
}
... 다음부터는 동일합니다.

gradlew clean war 명령으로 war 파일이 생성되었고
Tomcat에서도 ROOT.war로 파일명을 바꾸어서 잘 실행되는 듯 했습니다.

그런데 다음과 같은 서버 로그가 계속 찍힙니다.

java.lang.ClassCastException: class org.springframework.boot.web.servlet.support.ErrorPageFilter$ErrorWrapperResponse cannot be cast to class me.vectorx.spring.mvc.filter.VxApplicationResponseWrapper (org.springframework.boot.web.servlet.support.ErrorPageFilter$ErrorWrapperResponse and me.vectorx.spring.mvc.filter.VxApplicationResponseWrapper are in unnamed module of loader org.apache.catalina.loader.ParallelWebappClassLoader @1506f20f)

어떻게 해결하면 좋을꺼요?
조언 부탁드립니다.

고맙습니다.

혹시 LG CNS의 LENA 다운 받는 링크 있을까요?

**Comment by EY-Solution** [comment]
embedded tomcat 라이브러리 제거 설정이 빠져 있는 것으로 보입니다.
[https://github.com/EY-Solution/vectorx-templates-spring-bo Repository에 build.war.gradle ](https://github.com/EY-Solution/vectorx-templates-spring-bo/blob/main/build.war.gradle) 설정을 추가해놓았습니다.

최신 버전을 받으신 후, 아래의 명령어를 실행해보시면 됩니다.

```bash
./gradlew -b build.war.gradle clean war
```

또한 현재 내장 톰캣 버전은 9.0.83 버전이므로 해당 버전으로 구동해보시기 바랍니다.
아쉽지만 LENA 다운로드 링크는 저희도 가지고 있지 않습니다. CNS에 문의하시는 게 좋겠습니다.
