### ISSUE TITLE
WAR 빌드 및 배포 이어진 질문

### ISSUE THREAD

**Issue by dreamcometrue-color** [EY-Solution/EY-Solution.github.io#7]
안녕하세요

지난번에 답변 잘 보고 따라했습니다. 고맙습니다.

다음과 같은 순서로 진행하였습니다.
1. Tomcat 9.0.83 다운로드 및 압축 해제
2. 설명에 따라 프레임워크(vectorx-templates-spring-bo, vectorx-templates-nuxt-kendo-ui-bo) 최신 버전 다운로드
3. gradlew -b build.war.gradle clean war 명령으로 .war 파일로 빌드
4. 생성된 .war 파일을 ROOT.war 파일로 이름을 변경하여 Tomcat의 webapps 디렉토리에 복사
5. webapps 디렉토리 안의 ROOT 디렉토리 삭제
6. Tomcat의 bin 디렉토리로 이동
7. startup.bat 파일 실행
8. 로그인 및 게시판 접속

똑같은 현상이 발생하였습니다.
로그인과 게시판 접속은 잘 됩니다.
다만 서버 쪽에서 에러메시지가 출력됩니다.

java.lang.ClassCastException: class org.springframework.boot.web.servlet.support.ErrorPageFilter$ErrorWrapperResponse cannot be cast to class me.vectorx.spring.mvc.filter.VxApplicationResponseWrapper (org.springframework.boot.web.servlet.support.ErrorPageFilter$ErrorWrapperResponse and me.vectorx.spring.mvc.filter.VxApplicationResponseWrapper are in unnamed module of loader org.apache.catalina.loader.ParallelWebappClassLoader @5dcd8c7a)
        at me.vectorx.spring.mvc.logging.interfaces.VxWebInterfaceInfoStoreHelper.writeInboundInterfaceMessage(VxWebInterfaceInfoStoreHelper.java:275)
        at me.vectorx.spring.mvc.logging.interfaces.VxWebInboundInterfaceLoggingFilter.doFilterInternal(VxWebInboundInterfaceLoggingFilter.java:103)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
 
이에 대한 조언 부탁드립니다.
고맙습니다.

**Comment by EY-Solution** [comment]
안녕하세요 올려주신 내용을 검토한 결과 Request Dispatcher Type이 ERROR일 경우, 예외 처리가 필요한 것으로 판단하였습니다.
프레임워크 개선 이후 다시 comment 남기겠습니다. (차주 초 예상)

**Comment by EY-Solution** [comment]
`24.1.9-SNAPSHOT.4` 버전에서 개선되었습니다. 아래 URL에서 다운로드 가능합니다.

https://github.com/EY-Solution/vectorx-templates-spring-bo
