### ISSUE TITLE
REST API 호출 및 토큰

### ISSUE THREAD

**Issue by dreamcometrue-color** [EY-Solution/EY-Solution.github.io#8]
안녕하세요

매번 친절한 답변에 감사합니다
토큰을 어떤 형식으로 보내야 할지 문의 드립니다.

시나리오는 다음과 같습니다.

1. 로그인
POST /api/authentication/login HTTP/1.1
content-Type: application/json

{
    "userId": "admin",
    "userPw": "admin"
}

2. Response의 헤더에 mng-bo-token 과 mng-bo-rtoken 수신
3. 다음 Request의 헤더에 mng-bo-token 과 mng-bo-rtoken를 키로 하여 그 내용을 첨부하여 Request 송신
POST /api/samples/post/posts HTTP/1.1
content-Type: application/json
mng-bo-token: eyJhdXRoU3lz......
mng-bo-rtoken: 17218371773......

{

}

4. Request에 대한 Response 수신

이 시나리오에서 Response의 헤더에 mng-bo-token은 변경되어 계속 수신하고, mng-bo-rtoken은 변경되지 않고 수신합니다.

시나리오에서 mng-bo-token만 싣고 mng-bo-rtoken을 빼고 Request를 보내면 mng-bo-token 과 mng-bo-rtoken 가 모두 계속 변경된 값을 수신합니다.

반대로 mng-bo-token를 빼고 mng-bo-rtoken만 싣고  Request를 보내도 mng-bo-token 과 mng-bo-rtoken 가 모두 계속 변경된 값을 수신합니다.

궁금한 점은 다음과 같습니다.
1. mng-bo-token은 억세스 토큰 역할이고 mng-bo-rtoken은 리프레시 토큰 역할입니까?
2. 변경되어 수신하는 토큰 값을 다음 Request에 실어 보내는 것이 더 적절한 사용 방법입니까?
3. 이 토큰을 어떻게 사용하는 것이 가장 바람직한 시나리오입니까?
4. 토큰의 유효한 시간이 있을텐데 그 기간은 몇 초입니까?
5. 그 기간을 따로 설정할 수 있는 방법은 무엇입니까?

언제나 훌륭한 조언 감사드립니다.

**Comment by EY-Solution** [comment]
안녕하세요. 문의 하신 내용 답변 드립니다.

1. mng-bo-token은 억세스 토큰 역할이고 mng-bo-rtoken은 리프레시 토큰 역할입니까?
네 맞습니다.

2. 변경되어 수신하는 토큰 값을 다음 Request에 실어 보내는 것이 더 적절한 사용 방법입니까?
네 그렇게 진행하시면 됩니다. 다만 토큰 값이 리턴되지 않는 경우도 있으므로 이 경우에는 무시해야 합니다.

3. 이 토큰을 어떻게 사용하는 것이 가장 바람직한 시나리오입니까?
응답 시 별도로 저장하였다가 매번 Request에 요청하시면 됩니다. 다만 서버 상에서 인증 정보가 필요 없는 경우는 안보내도 됩니다.

4. 토큰의 유효한 시간이 있을텐데 그 기간은 몇 초입니까?
관련 설정 가이드는 https://vectorx.notion.site/178f17b29fe0430ba6c45476485714da 를 참고하시면 됩니다.
여기서 vx.management.bo.authentication.access-valid-second, vx.management.bo.authentication.refresh-valid-seconds 가 관련 설정입니다.

템플릿에도 관련 설정 정보를 추가해놓았으니 참고해서 보시면 됩니다.
https://github.com/EY-Solution/vectorx-templates-spring-bo/blob/main/src/main/resources/application.yml#L54

5. 그 기간을 따로 설정할 수 있는 방법은 무엇입니까?
4번 항목 참고해서 세팅하시면 됩니다.
