### ISSUE TITLE
권한 설정

### ISSUE THREAD

**Issue by dreamcometrue-color** [EY-Solution/EY-Solution.github.io#9]
안녕하세요
매번 빠르고 친절한 답변 감사드립니다.

VectorX Framework에서 사용자 권한 설정 판단할 수 있을만한 메뉴는
1. 메뉴관리의 "권한 유형(일반, 기능권한, 없음)과 "권한 범위(권한, 기초 설정, 기타)"
2. 사용자관리의 "구분(개인정보취급, 일반내부사용자, 일반외부사용자, 기타)"
3. 권한 그룹 관리
4. 그룹 관리
등이 있습니다.

그런데 사용 방법을 잘 모르겠습니다.
아직 구현 중이신 부분이 있으시더라도 향후 계획 중인 사용 방법을 알고 싶습니다.

가령 예를 들어
사용자별 혹은 그룹별 메뉴 접근 권한
접근 이후 컨텐츠의 읽기, 쓰기, 수정, 삭제 등의 권한 설정
등이 가능할까요? 그렇다면 어떻게 할까요?

고맙습니다.

**Comment by EY-Solution** [comment]
문의 주신 내용 답변 드립니다.

1. 메뉴관리의 "권한 유형(일반, 기능권한, 없음)과 "권한 범위(권한, 기초 설정, 기타)"
권한 유형의 의미
  일반 (메뉴접근 권한으로 제어)
  기능권한 (메뉴접근 + 각 기능별 권한 제어)
  없음 (권한 체크하지 않음 - 권한이 부여되지 않아도 모든 사용자의 접근 가능함.)

권한 범위의 의미
  설정 메뉴가 어떤 권한 범주에 있는지 설정함. 단순 레포트를 뽑기 위한 기능.
  권한 현황에서 확인할 수 있음.

  권한 상태 조회 매뉴얼 : https://www.notion.so/vectorx/08ff4eedd4fb4d6b80683478b276d880
  kendo ui 의 경우는 이전 중입니다.

2. 사용자 관리의 구분
  사용자 관리의 구분은 백오피스 스프링 설정에서 권한 그룹 별로 특정 구분의 사용자만 배정할 수 있도록 설정할 수 있습니다.
  매뉴얼 참조 : https://www.notion.so/vectorx/c6c1f5c10abc4ce496fae7f0279c7a8c
  
3. 권한 그룹 관리
    매뉴얼 참조 : https://vectorx.notion.site/32b7e2aaf5d7443ca166c80c00c6b9ae

4. 그룹 관리
     매뉴얼 참조 : https://www.notion.so/vectorx/351cb8753f0a401f8eb6c64ae3b18b4a


5. 가령 예를 들어
사용자별 혹은 그룹별 메뉴 접근 권한
접근 이후 컨텐츠의 읽기, 쓰기, 수정, 삭제 등의 권한 설정
등이 가능할까요? 그렇다면 어떻게 할까요?

메뉴의 기능별로 권한을 제어하고 싶은 것으로 이해됩니다.
1) 메뉴 관리에서 권한 유형을 "기능권한"으로 설정합니다.
2) 원하는 기능 아이디와 이름을 입력하여 저장합니다.
3) 권한 관리에서 지정된 기능별로 권한을 설정합니다.
4) 아래 권한 확인 메소드를 사용하여 개발자가 기능별로 접근 제어 수행.

- 메뉴 관리 매뉴얼 : https://www.notion.so/vectorx/fdf0ed5b618b4088a3c3a288a1df3e82
- 권한 관리 메뉴얼 : https://www.notion.so/vectorx/351cb8753f0a401f8eb6c64ae3b18b4a
- 권한 확인 메소드 : https://vectorx.notion.site/2f9baf3a03c3450599f7841975a1466c#656030e566364a3cbc309993672de8c9

확인해보시고 추가적인 문의가 있으시면 말씀 주세요.
